### PR TITLE
Testing/2.8.0

### PR DESCRIPTION
**Pull request by danimtb**
Updated recipe, updated to version 2.8.0 of the library, added CMake, reviewed CI config

### CODE REVIEW

**Comment by danimtb** [comment]
This is a simple C library that could be a good one to have in conan-center. I have started to see how it works as it is an optional dependency of libgit2.

Its current status is near to be building in all platforms (haven't checked appveyor but it was working in my windows machine).

I encourage you to revisit it and improve it to be in conan-center.
Thank you!

**Comment by danimtb** [comment]
Dont like too much that generic _CMakeLists.txt_ in this PR. I just copied it from an open PR in the http_parser repo but I think it is too much for thus a _.h_ and a _.c_.

Maybe we could add a simpler one. WDYT @theirix ?

**Comment by theirix** [comment]
Thanks for the great refactoring!
I have experienced a few problems with building http-parser because upstream doesn't care about building it anywhere except nodejs and just ignores tickets and it smells. That's the reason why I don't propose such library to conan-center.

Static builds, installing stuff are addressed in the `Makefile` patch. I don't know are they in proposed CMake build but I'll check it later this week.

**Comment by theirix** [comment]
Oh, didn't see your previous message! I'll make a simpler one with static build. Maybe we should pitch build issues in upstream :)

**Comment by danimtb** [comment]
Thanks for the answer!
Didnt know those issues with the makefile. Just thouth it was two files LOL

Check the proposed CMakeLists.txt, but I think it is not doing anything special...

IMO, better to have that static build than nothing but I have no idea if we are gonna lose any library functionality.

Please have a look when you have the time and ping me back :)

**Comment by theirix** [comment]
Thank you again for the idea. As a result I picked up one of the cmakes from pull requests to http-parser itself. They were all incomplete so I updated them a little. Now http-parsers builds fine on Linux and macOS (static and shared) and on Windows (static only).
Also I moved repository to bincrafters organization - https://github.com/bincrafters/conan-http-parser

**Comment by danimtb** [comment]
Thanks a lot @theirix for moving this forward and for the dedication! Hope to see the inclusion request to conan-center soon 😄

**Pull request closed without merging**
